/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/brandTheme.ts
 * Command: astryx theme build src/theme/brandTheme.ts --out src/theme/brandTheme.css
 * Generated: 2026-07-28T07:33:37.319Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
