/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/brandTheme.ts
 * Command: astryx theme build src/theme/brandTheme.ts --out src/theme/brandTheme.css
 * Generated: 2026-07-28T13:53:23.841Z
 */

/// <reference path="./family-defense.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const familyDefenseTheme: DefinedTheme;
